Concordium/cryptox-android

README.md
Actualize download links in Readme
- Add Testnet GooglePlay download link
- Add GitHub download links for Mainnet and Testnet
=> Actualize download links in Readme

CHANGELOG.md, app/src/main/assets/terms.html, app/src/main/res/values/strings.xml
Actualize End User License Terms and Privacy Policy URL.
- Actualized End User License Terms and Privacy Policy URL
=> PRO-263 Update terms and privacy policy

CHANGELOG.md, app/src/main/java/com/concordium/wallet/data/model/RemoteTransaction.kt, app/src/main/java/com/concordium/wallet/data/model/Transaction.kt, app/src/main/java/com/concordium/wallet/data/util/TransactionMappingExtensions.kt, app/src/main/java/com/concordium/wallet/ui/account/common/accountupdater/AccountUpdater.kt
_Describe the purpose of the pull request, link to issue describing the problem, etc.
- Fix processing transfers as unshieldings
- Remove unused `Transaction` methods
=> AND-3 Fix visually increasing the balance after sending CCD

app/src/main/java/com/concordium/wallet/data/model/Token.kt, app/src/main/java/com/concordium/wallet/data/util/CurrencyUtil.kt, app/src/main/java/com/concordium/wallet/ui/cis2/SendTokenActivity.kt, app/src/main/java/com/concordium/wallet/ui/cis2/SendTokenReceiptActivity.kt, app/src/main/java/com/concordium/wallet/ui/cis2/SendTokenViewModel.kt, app/src/main/java/com/concordium/wallet/ui/cis2/TokenDetailsActivity.kt, app/src/main/java/com/concordium/wallet/ui/cis2/TokensAccountDetailsAdapter.kt, app/src/main/java/com/concordium/wallet/ui/cis2/TokensViewModel.kt, app/src/main/java/com/concordium/wallet/ui/cis2/manage/ManageTokensSelectionAdapter.kt, app/src/main/java/com/concordium/wallet/ui/cis2/manage/ManageTokensTokenDetailsFragment.kt
Refactor the model to make working with it easier when implementing CIS-2 notifications.
- Get rid of useless fields
- Simplify construction
=> Refactor Token model

app/src/main/java/com/concordium/wallet/ui/onramp/CcdOnrampSiteRepository.kt
Add Gate.io as an onramp option
- Add Gate.io as an onramp option
=> Add Gate.io as an onramp option

app/src/main/res/values/strings.xml
Get rid of "anonymous" in the tracking motivation message.
- Update the tracking motivation message
=> Rephrase tracking motivation

app/src/main/assets/delegation_intro_flow_en_6.html
Remove incorrect statement from the delegation guide
- Remove incorrect statement from a guide
=> AND-72 Remove incorrect statement from the delegation guide

app/src/main/java/com/concordium/wallet/ui/account/earn/EarnInfoActivity.kt, app/src/main/java/com/concordium/wallet/ui/bakerdelegation/common/CooldownView.kt, app/src/main/java/com/concordium/wallet/ui/bakerdelegation/common/StatusActivity.kt, app/src/main/res/layout/activity_earn_info.xml, app/src/main/res/layout/item_cooldown.xml, app/src/main/res/layout/view_cooldown.xml
Show cooldowns on the Earn screen when the delegation or validator is stopped
- Make the cooldown card a view
- Show cooldowns on the Earn screen
=> AND-71 Show cooldowns on the earn screen

CHANGELOG.md, app/src/main/assets/baker_remove_intro_flow_en_1.html, app/src/main/assets/baker_update_intro_flow_en_2.html, app/src/main/assets/delegation_remove_flow_en_1.html, app/src/main/assets/delegation_update_flow_en_3.html, app/src/main/res/values/strings.xml
Update cooldown text
Update validation/delegation text notices
=> AND-73 Update cooldown text

CHANGELOG.md, app/build.gradle, app/src/main/java/com/concordium/wallet/core/notifications/UpdateNotificationsSubscriptionUseCase.kt
Crash on launch when Google Play Services is disabled
Add check if Google Play Services is enabled
=> Fix crash on launch when Google Play Services is disabled

README.md
Join BrowserStacks open source sponsorship program, to enable automatic testing.
```
You are one step away from activating your subscription:
Please incorporate the text: 'This project is tested with BrowserStack' without quotes within the project's README.md file. Please merge this change into the main/ master branch at your earliest convenience to proceed.
```
Add text required to join BrowserStacks open source sponsorship program.
=> Add text to README to join BrowserStack open source program

app/src/main/java/com/concordium/wallet/data/backend/InMemoryCookieJar.kt, app/src/main/java/com/concordium/wallet/data/backend/ProxyBackendConfig.kt
This must fix inconsistencies when querying transactions by submission ID caused by load balancing.
- Accept wallet proxy cookies
=> AND-120 Fix showing created account as instantly failed sometimes

CHANGELOG.md, app/src/main/java/com/concordium/wallet/core/notifications/TransactionNotificationsManager.kt
_Describe the purpose of the pull request, link to issue describing the problem, etc.
- Fix incorrect check if CIS-2 tx notifications are on
=> AND-115 Fix CIS-2 notifications not working if CCD notifications are disabled

app/src/main/java/com/concordium/wallet/data/util/CurrencyUtil.kt, app/src/main/java/com/concordium/wallet/ui/account/accountsoverview/AccountsOverviewFragment.kt, app/src/main/java/com/concordium/wallet/ui/account/accountsoverview/AccountsOverviewViewModel.kt, app/src/main/java/com/concordium/wallet/ui/bakerdelegation/baker/BakerPoolSettingsActivity.kt, app/src/main/res/values/strings.xml
Incorrect commission number format at Register Validator screen
- Fix commission number format
- Update animation and popups logic
=> Bugfix/AND-136 Fix register validator screen

app/src/main/java/com/concordium/wallet/data/room/Recipient.kt, app/src/main/java/com/concordium/wallet/ui/cis2/SendTokenActivity.kt, app/src/main/java/com/concordium/wallet/ui/recipient/recipientlist/RecipientListActivity.kt, app/src/main/java/com/concordium/wallet/ui/recipient/recipientlist/RecipientListViewModel.kt, app/src/main/java/com/concordium/wallet/util/Extensions.kt
Fix address book screen after the redesign.
- Fix crash when opening the address book from the More screen
- Do not show the Continue button if not selecting a recipient
=> Fix address book screen

CHANGELOG.md, app/build.gradle
Merge release 1.6.1
Update version to 1.6.1
=> Merge release 1.6.1

app/src/main/assets/baker_intro_flow_en_4.html, app/src/main/java/com/concordium/wallet/ui/bakerdelegation/baker/introflow/BakerRegistrationIntroFlow.kt, app/src/main/res/values/strings.xml
- Fix missing Suspension details in the Validator Registration text
- Added missing Suspension details to the Validator Registration text
=> AND-149 Fix missing Suspension details in the Validator Registration text

app/src/main/res/values/strings.xml
The privacy policy link has changed
Fix privacy policy link
=> Update privacy policy link

app/src/main/java/com/concordium/wallet/ui/bakerdelegation/delegation/DelegationRegisterAmountActivity.kt, app/src/main/java/com/concordium/wallet/ui/bakerdelegation/delegation/DelegationRegisterConfirmationActivity.kt, app/src/main/java/com/concordium/wallet/ui/bakerdelegation/delegation/DelegationRegisterPoolActivity.kt, app/src/main/res/layout/activity_delegation_registration_confirmation.xml, app/src/main/res/values/strings.xml
Fix UI bugs
- Fix DelegationRegisterAmountActivity
- Fix DelegationRegisterConfirmationActivity
- Fix DelegationRegisterPoolActivity
=> Fix earn flow UI bugs

CHANGELOG.md, app/build.gradle, app/src/main/java/com/concordium/wallet/ui/account/accountdetails/AccountDetailsFragment.kt, app/src/main/res/layout/activity_account_details.xml
Implement swipe to refresh feature
- Added Pull to refresh feature on Home screen
=> Swipe to refresh

app/src/main/java/com/concordium/wallet/ui/bakerdelegation/delegation/DelegationRegisterConfirmationActivity.kt, app/src/main/res/values/strings.xml
Update delegation confirmation text
- Change delegation confirmation text
=> Update delegation confirmation text

CHANGELOG.md, app/src/main/res/layout/delegation_validation_action_buttons.xml
Cutting off a text on the delegation action button
- Fix  delegation action button layout
=> Fix action buttons label

.github/workflows/end_to_end_tests.yml, cryptox-android-autotests/src/test/java/config/CustomTestListener.java, cryptox-android-autotests/src/test/java/cryptox_AndroidTest/baseClass.java
_Describe the purpose of the pull request, link to issue describing the problem, etc.
_Describe the changes that were needed.
_Remove if not applicable.
By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf
=> Slack notification fix - Added capability to get WebHook URL from secrets. 

.github/workflows/end_to_end_tests.yml, cryptox-android-autotests/src/test/java/config/CustomTestListener.java
_Describe the purpose of the pull request, link to issue describing the problem, etc.
_Describe the changes that were needed.
_Remove if not applicable.
By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf
=> added capability to store failure artifacts in gitHub

app/src/main/java/com/concordium/wallet/core/tokens/TokensInteractor.kt, app/src/main/java/com/concordium/wallet/data/model/CCDToken.kt, app/src/main/java/com/concordium/wallet/ui/cis2/TokenDetailsActivity.kt, app/src/main/java/com/concordium/wallet/ui/cis2/TokensListViewModel.kt
Incorrect balance in tokens list on the Home screen
Show total balance in tokens list on the Home screen
=> Show total balance on tokens list
