Concordium/cryptox-android

CHANGELOG.md
app/build.gradle
app/src/main/java/com/concordium/wallet/ui/MainActivity.kt
app/src/main/java/com/concordium/wallet/ui/account/accountsoverview/AccountsOverviewFragment.kt
app/src/main/java/com/concordium/wallet/ui/account/accountsoverview/AccountsOverviewViewModel.kt
app/src/main/java/com/concordium/wallet/ui/identity/identityproviderlist/IdentityProviderListActivity.kt
app/src/main/java/com/concordium/wallet/ui/identity/identityproviderlist/IdentityProviderListViewModel.kt

Fix a way to get into an empty wallet without confirming the seed phrase, leading to creation of a new file-based wallet.
- Deny creation of the first identity if V0 key creation is in use;
- Fix not continuing initial setup if no auth needed;

WAL2-87 Fix ability to create a new file-based wallet

---

CHANGELOG.md
app/src/main/java/com/concordium/wallet/ui/welcome/WelcomePromoViewModel.kt

The "Watch video" link on the welcome screen now opens the account creation tutorial.
- The "Watch video" link on the welcome screen now opens the account creation tutorial.

Actualize "Watch video" link

---

app/src/main/java/com/concordium/wallet/data/room/Account.kt

- Fix showing read-only accounts on the unshielding screen.
- Do not consider read-only accounts for unshielding.

Do not consider read-only accs for unshielding

---

app/src/main/java/com/concordium/wallet/core/authentication/Session.kt
app/src/main/java/com/concordium/wallet/data/preferences/AuthPreferences.kt

Show unshielding notice once per app start instead of showing it once at all.
- Store unshielding notice shown flag in the session

AND-31 Show unshielding notice once per app start

---

app/src/main/java/com/concordium/wallet/ui/more/unshielding/UnshieldingAccountsActivity.kt
app/src/main/java/com/concordium/wallet/ui/more/unshielding/UnshieldingActivity.kt

After cancel, app should route to the parent view.
- Do not finish unshielding screens on auth cancel

AND-30 Do not finish unshielding screens on auth cancel

---

app/src/main/java/com/concordium/wallet/ui/more/unshielding/UnshieldingAccountsActivity.kt
app/src/main/java/com/concordium/wallet/ui/more/unshielding/UnshieldingAccountsViewModel.kt
app/src/main/java/com/concordium/wallet/ui/more/unshielding/UnshieldingViewModel.kt
app/src/main/res/layout/activity_unshielding_accounts.xml
app/src/main/res/values/strings.xml

Fix missing Done button at the end of the unshielding flow. Ensure the unshielding is not requested right away after all the accounts have been unshielded.
- Add Done button to the unshielding accounts screen
- Remove useless added amount check in unshielding
- Run account update when unshielding completes

AND-34 Add missing button at the end of the unshielding flow

---

CHANGELOG.md
app/src/main/java/com/concordium/wallet/data/room/Recipient.kt
app/src/main/java/com/concordium/wallet/ui/account/common/NewAccountViewModel.kt
app/src/main/java/com/concordium/wallet/ui/account/common/accountupdater/AccountUpdater.kt
app/src/main/java/com/concordium/wallet/ui/common/identity/IdentityUpdater.kt
app/src/main/java/com/concordium/wallet/ui/identity/identityproviderwebview/IdentityProviderWebViewViewModel.kt
app/src/main/java/com/concordium/wallet/ui/more/import/ImportViewModel.kt
app/src/main/java/com/concordium/wallet/ui/passphrase/recoverprocess/RecoverProcessViewModel.kt

Fix adding accounts to the address book with an empty name
- If adding a recipient automatically created from an account, use the name getter with fallback to avoid empty names

AND-36 Fix adding accounts to the address book with an empty name

---

CHANGELOG.md
app/build.gradle
app/src/main/res/layout/activity_recover_wallet.xml
app/src/main/res/layout/fragment_pass_phrase_recover_input.xml

Fix button to paste the seed phrase is hidden under on-screen keyboard.
- Make the paste button on the recovery phrase input screen attached to the top of the keyboard hence remains always visible

AND-33 Fix phrase paste button visibility

---

app/src/main/java/com/concordium/wallet/data/backend/ProxyBackend.kt
app/src/main/java/com/concordium/wallet/data/backend/repository/IdentityProviderRepository.kt
app/src/main/java/com/concordium/wallet/ui/identity/identityproviderlist/IdentityProviderListViewModel.kt
app/src/main/java/com/concordium/wallet/ui/passphrase/recoverprocess/RecoverProcessViewModel.kt

Only show Global FinReg company ID provider when the wallet is compatible.
- Replace V1 `ip_info` endpoint with V2
- Change `useV1` flag in identity provider repo to `useLegacy` to avoid V1-V2 confusion 

AND-61 Explicitly allow company ID in ID providers request

---

app/src/main/java/com/concordium/wallet/data/util/CurrencyUtil.kt
app/src/main/java/com/concordium/wallet/ui/cis2/TokenDetailsActivity.kt
app/src/main/java/com/concordium/wallet/ui/cis2/manage/ManageTokensSelectionAdapter.kt
app/src/main/java/com/concordium/wallet/ui/cis2/manage/ManageTokensTokenDetailsFragment.kt

Fix showing 'null' decimals on token details, an error brought by the CIS-2 notifications feature.
- Show 0 instead of 'null' when a token has no decimals in the metadata

Fix showing 'null' decimals on token details

---

app/src/main/java/com/concordium/wallet/ui/more/notifications/NotificationsPreferencesActivity.kt
app/src/main/java/com/concordium/wallet/ui/more/notifications/NotificationsPreferencesViewModel.kt

Fix presenting notification settings state in case of backend errors
- Prevent changing the state locally before getting a successful response from the server

AND-63 Fix presenting notification settings state

---

CHANGELOG.md
app/src/main/java/com/concordium/wallet/data/model/BakerDelegationData.kt
app/src/main/java/com/concordium/wallet/data/model/ChainParameters.kt
app/src/main/java/com/concordium/wallet/ui/bakerdelegation/baker/BakerRegistrationConfirmationActivity.kt
app/src/main/java/com/concordium/wallet/ui/bakerdelegation/baker/BakerRegistrationOpenActivity.kt
app/src/main/java/com/concordium/wallet/ui/bakerdelegation/common/DelegationBakerViewModel.kt

Fix inability to configure a validator closed for delegation.
- Move `bakingCommissionRate` and `transactionCommissionRate` from the `ChainParameters` model to avoid confusion (those fields are not returned by the proxy)
- Use max range value as a rate instead of null if the validator is closed for delegation. Null value caused failure of the transaction

AND-67 Fix validator setup failure

---

CHANGELOG.md
app/src/main/java/com/concordium/wallet/core/notifications/FcmNotificationsService.kt
app/src/main/java/com/concordium/wallet/core/notifications/TransactionNotificationsManager.kt
app/src/main/java/com/concordium/wallet/data/ContractTokensRepository.kt
app/src/main/java/com/concordium/wallet/data/model/Token.kt
app/src/main/java/com/concordium/wallet/data/room/ContractToken.kt
app/src/main/java/com/concordium/wallet/data/room/ContractTokenDao.kt
app/src/main/java/com/concordium/wallet/ui/account/accountdetails/AccountDetailsActivity.kt
app/src/main/java/com/concordium/wallet/ui/cis2/TokenDetailsActivity.kt
app/src/main/java/com/concordium/wallet/ui/cis2/TokensAccountDetailsAdapter.kt
app/src/main/java/com/concordium/wallet/ui/cis2/TokensFragment.kt
app/src/main/java/com/concordium/wallet/ui/cis2/TokensViewModel.kt
app/src/main/java/com/concordium/wallet/ui/cis2/defaults/DefaultFungibleToken.kt
app/src/main/java/com/concordium/wallet/ui/cis2/defaults/DefaultTokensManagerFactory.kt
app/src/main/java/com/concordium/wallet/ui/cis2/manage/ManageTokensSelectionFragment.kt
app/src/main/res/layout/fragment_tokens.xml

Notification bugfix
- Fix CIS-2 tokens empty state
- Fix CIS-2 tokens notification destination route

AND-66 Notification bugfix

---

app/src/main/java/com/concordium/wallet/core/notifications/UpdateNotificationsSubscriptionUseCase.kt
app/src/main/java/com/concordium/wallet/data/backend/notifications/NotificationsBackend.kt
app/src/main/java/com/concordium/wallet/data/backend/notifications/UpdateSubscriptionRequest.kt

Use the separate endpoint for unsubscription, so the token gets actually removed on the server.
- Use the `unsubscrube` endpoint to unsubscribe from all the notifications

Make notification unsubscription work

---

CHANGELOG.md
app/src/main/java/com/concordium/wallet/ui/walletconnect/WalletConnectVerifiablePresentationRequestHandler.kt
app/src/main/java/com/concordium/wallet/ui/walletconnect/WalletConnectViewModel.kt

Fix a crash loop caused by a malformed WalletConnect verifiable presentation request
- Check WC ID proof request nullability
- Handle unexpected WC session request handling errors
- Await the WC connection before sending responses

AND-79 Fix WC crash loop

---

app/src/main/java/com/concordium/wallet/ui/account/accountdetails/AccountDetailsViewModel.kt

Fix increasing shielded balance when requesting a CCD drop on testnet.
- Do not process CCD drop as shielded transfer

Fix processing CCD drop as shielded transfer

---

CHANGELOG.md
app/src/main/java/com/concordium/wallet/ui/bakerdelegation/common/DelegationBakerViewModel.kt

Fix showing incorrect commission rates on the update validator stake update confirmation screen
- Do not show commissions on validator stake update

AND-90 Do not show commissions on validator stake update

---

CHANGELOG.md
app/src/main/java/com/concordium/wallet/ui/onramp/CcdOnrampSitesActivity.kt

Skip onramp account selection/copying for Concordex
- When going to Concordex DEX, there's no need to select or copy account address, 
as it is a WalletConnect-based DEX which fetches the wallet data itself.

Skip onramp account selection/copying for Concordex

---

CHANGELOG.md
app/src/main/java/com/concordium/wallet/ui/onramp/CcdOnrampAccountsActivity.kt
app/src/main/java/com/concordium/wallet/ui/onramp/CcdOnrampSite.kt
app/src/main/java/com/concordium/wallet/ui/onramp/CcdOnrampSiteRepository.kt
app/src/main/java/com/concordium/wallet/ui/onramp/CcdOnrampSitesActivity.kt
app/src/main/java/com/concordium/wallet/ui/onramp/OpenCcdOnrampSiteWithAccountUseCase.kt
app/src/main/java/com/concordium/wallet/ui/onramp/swipelux/SwipeluxSettingsHelper.kt
app/src/main/java/com/concordium/wallet/ui/onramp/swipelux/SwipeluxWidgetConfig.kt

Update Swipelux onramp flow
Use the new customizable page allowing pre-setting the address and the token for the Swipelux payment gateway

Feature/AND-113 update Swipelux onramp flow

---

CHANGELOG.md
app/src/main/java/com/concordium/wallet/core/notifications/UpdateNotificationsSubscriptionUseCase.kt

Fix crash when first launching the app and creating a wallet offline
- Expect getting the Firebase token to fail
- Trying to update the subscription without the token is no longer considered successful

AND-118 Fix crash when first launching the app and creating a wallet offline

---

app/src/main/java/com/concordium/wallet/data/util/CurrencyUtil.kt
app/src/main/java/com/concordium/wallet/ui/bakerdelegation/baker/BakerRegisterAmountActivity.kt
app/src/main/java/com/concordium/wallet/ui/bakerdelegation/delegation/DelegationRegisterAmountActivity.kt

Wrong value of pasted validation/delegation state
Fixed incorrect value when updating delegation and validation state

Fixed incorrect value when updating delegation and validation state

---

app/src/main/java/com/concordium/wallet/ui/account/accountsoverview/AccountsOverviewFragment.kt
app/src/main/java/com/concordium/wallet/ui/account/accountsoverview/AccountsOverviewViewModel.kt
app/src/main/java/com/concordium/wallet/ui/welcome/WelcomeActivity.kt
app/src/main/java/com/concordium/wallet/ui/welcome/WelcomeViewModel.kt

Notification Permission popup only appears when user relaunch the App or navigate back to main screen
Notification Permission popup has been moved to the WelcomeScreen

Change notification popup logic

---

CHANGELOG.md
app/src/main/java/com/concordium/wallet/ui/bakerdelegation/baker/BakerRegistrationOpenActivity.kt
app/src/main/java/com/concordium/wallet/ui/more/about/AboutActivity.kt
app/src/main/res/layout/activity_about.xml
app/src/main/res/values/strings.xml

Add ability to see the Terms as well as the Privacy policy once the wallet is set up. Add the corresponding links to the About screen
- Added the links to the About screen
- Fixed not clickable links on some screens
- Fixed incorrect support email in some places

AND-144 Add Terms and Privacy policy to the About screen

---

app/build.gradle
app/src/main/java/com/concordium/wallet/AppConfig.kt
app/src/main/java/com/concordium/wallet/core/AppCore.kt
app/src/main/java/com/concordium/wallet/data/backend/GrpcBackendConfig.kt
app/src/main/java/com/concordium/wallet/data/backend/ProxyBackendConfig.kt
app/src/main/java/com/concordium/wallet/data/cryptolib/CreateTransferInput.kt
app/src/main/java/com/concordium/wallet/data/model/AccountData.kt
app/src/main/java/com/concordium/wallet/data/model/BakerDelegationData.kt
app/src/main/java/com/concordium/wallet/ui/bakerdelegation/common/DelegationBakerViewModel.kt
app/src/main/java/com/concordium/wallet/ui/cis2/SendTokenViewModel.kt
app/src/main/java/com/concordium/wallet/ui/common/BackendErrorHandler.kt
app/src/main/java/com/concordium/wallet/ui/connect/uni_ref/UniRefViewModel.kt
app/src/main/java/com/concordium/wallet/ui/more/unshielding/UnshieldingViewModel.kt
app/src/main/res/values/strings.xml

Prepare underlying logic of validation and delegation for Protocol 8 changes.
- Update Concordium SDK to 10.0.0
- Add ability to use GRPC client in the app
- Use SDK and GRPC for validation and delegation configuration transactions
- Remove validation/delegation fields from CreateTransferInput

Prepare for Protocol 8

---

app/src/main/java/com/concordium/wallet/core/AppCore.kt
app/src/main/java/com/concordium/wallet/data/backend/ProxyBackend.kt
app/src/main/java/com/concordium/wallet/data/backend/repository/ProxyRepository.kt
app/src/main/java/com/concordium/wallet/data/model/AccountSubmissionStatus.kt
app/src/main/java/com/concordium/wallet/data/model/SubmissionStatusResponse.kt
app/src/main/java/com/concordium/wallet/ui/account/accountdetails/AccountReleaseScheduleViewModel.kt
app/src/main/java/com/concordium/wallet/ui/account/common/NewAccountViewModel.kt
app/src/main/java/com/concordium/wallet/ui/account/common/accountupdater/AccountUpdater.kt
app/src/main/java/com/concordium/wallet/ui/bakerdelegation/common/DelegationBakerViewModel.kt
app/src/main/java/com/concordium/wallet/ui/connect/uni_ref/UniRefViewModel.kt
app/src/main/java/com/concordium/wallet/ui/transaction/transactiondetails/TransactionDetailsViewModel.kt

Fix inability to submit SDK transactions via the public GRPC node when it is being spammed.
- Add proxy endpoint to submit serialized transactions
- Submit baker/delegation transaction via the proxy
- Clean up submission status proxy endpoints
- Add deprecation warning (for visibility) to the GRPC client getter

Submit transactions through proxy

---

app/src/main/java/com/concordium/wallet/App.kt
app/src/main/java/com/concordium/wallet/data/backend/ProxyBackend.kt
app/src/main/java/com/concordium/wallet/data/backend/price/TokenPriceModule.kt
app/src/main/java/com/concordium/wallet/data/backend/price/TokenPriceRepository.kt
app/src/main/java/com/concordium/wallet/data/backend/repository/ProxyRepository.kt
app/src/main/java/com/concordium/wallet/data/model/Token.kt
app/src/main/java/com/concordium/wallet/data/util/CurrencyUtil.kt
app/src/main/java/com/concordium/wallet/ui/account/accountdetails/AccountDetailsFragment.kt
app/src/main/java/com/concordium/wallet/ui/account/earn/EarnViewModel.kt
app/src/main/java/com/concordium/wallet/ui/bakerdelegation/common/DelegationBakerViewModel.kt
app/src/main/java/com/concordium/wallet/ui/cis2/SendTokenViewModel.kt
app/src/main/java/com/concordium/wallet/ui/cis2/TokensAccountDetailsAdapter.kt
app/src/main/java/com/concordium/wallet/ui/cis2/TokensViewModel.kt
app/src/main/java/com/concordium/wallet/ui/walletconnect/WalletConnectSignTransactionRequestHandler.kt

Do not load chain params 5-6 times on account details screen update.
- Added `TokenPriceRepository` to load and cache CCD:EUR price. The price is cached in memory for 1 hour
- Unified `ProxyRepository` chain parameters getter – only suspended version left
- `TokenPriceRepository` is being injected where needed with Koin (there already was unconfigured Koin in the app)
- Therefore `chainParameters` request for fetching CCD:EUR price gets executed once per hour, on demand
- `numerator` and `denominator` in `Token` replaced with optional `eurPerUnit: SimpleFraction?`
- `CurrencyUtil.toEURRate()` now accepts `SimpleFraction` as price per unit
- `0 EUR` is no longer shown if the price can't be loaded

Reduce chain parameters reload

---

app/src/main/java/com/concordium/wallet/ui/onramp/swipelux/SwipeluxSettingsHelper.kt

Update the key for the KYC flow to become is easier.
_Describe the changes that were needed.

Update Swipelux key

---

CHANGELOG.md
app/src/main/java/com/concordium/wallet/ui/onramp/CcdOnrampItemAdapter.kt
app/src/main/java/com/concordium/wallet/ui/onramp/CcdOnrampListItem.kt
app/src/main/java/com/concordium/wallet/ui/onramp/CcdOnrampSite.kt
app/src/main/java/com/concordium/wallet/ui/onramp/CcdOnrampSiteRepository.kt
app/src/main/java/com/concordium/wallet/ui/onramp/CcdOnrampSitesViewModel.kt
app/src/main/res/layout/list_item_ccd_onramp_disclaimer.xml
app/src/main/res/layout/list_item_ccd_onramp_exchanges_notice.xml
app/src/main/res/layout/list_item_ccd_onramp_header.xml
app/src/main/res/layout/list_item_ccd_onramp_section.xml
app/src/main/res/values/strings.xml

To streamline the UI/UX on both platforms, we need to remove the list of currently supported exchanges within the CryptoX
Instead, we would show a message linking users to our website: “List of supported exchanges can be found at concordium.com/ccd-wallet
- On the Buy screen, exchange sections are replaced with an external link
- Reduced vertical paddings on the screen
- Fixed the disclaimer text alignment 

WAL-1025 Remove list of exchanges

---

app/src/main/java/com/concordium/wallet/ui/walletconnect/WalletConnectViewModel.kt

Prevent theoretical situation when the wallet accepts a session for many chains, while in fact it supports only one of them.

Approve WC session specifying the chain

---

CHANGELOG.md
app/src/main/java/com/concordium/wallet/core/tokens/TokensInteractor.kt
app/src/main/java/com/concordium/wallet/core/tokens/TokensInteractorModule.kt

Fix not showing tokens after switching wallets
- Do not cache repos in long living TokensInteractor, as it breaks wallet switching – it keeps using instances for the previous wallet.

Fix not showing tokens after switching wallets
